# Generated by Django 3.2.4 on 2021-07-02 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0003_auto_20210702_0925'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comentarios',
            new_name='Comentario',
        ),
        migrations.AlterModelOptions(
            name='comentario',
            options={'ordering': ['-created'], 'verbose_name': 'Comentario', 'verbose_name_plural': 'Comentarios'},
        ),
    ]
