# Generated by Django 3.2.4 on 2021-06-27 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('apellidopat', models.CharField(max_length=20)),
                ('apellidomat', models.CharField(max_length=20)),
                ('estudiante', models.BooleanField()),
                ('sexo', models.CharField(max_length=10)),
                ('correo', models.EmailField(max_length=254)),
                ('telefono', models.TextField()),
                ('curso', models.TextField()),
                ('mensaje', models.TextField()),
                ('calificacion', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
