# Generated by Django 3.2.4 on 2021-06-27 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cursos', '0002_delete_curso'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cursos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('descripcion', models.TextField()),
                ('precio', models.IntegerField()),
                ('duracion_horas', models.IntegerField()),
                ('asesor', models.CharField(max_length=30)),
                ('correo_asesor', models.EmailField(max_length=254)),
                ('descuento', models.BooleanField()),
                ('porcentaje_descuento', models.DecimalField(decimal_places=2, max_digits=3)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
