# Generated by Django 3.2.4 on 2021-07-06 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0003_cursos'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cursos',
            options={'ordering': ['created'], 'verbose_name': 'Cursos', 'verbose_name_plural': 'Cursos'},
        ),
        migrations.AddField(
            model_name='cursos',
            name='imagen',
            field=models.ImageField(null=True, upload_to='fotos', verbose_name='Fotografia'),
        ),
        migrations.AlterField(
            model_name='cursos',
            name='asesor',
            field=models.CharField(max_length=30, verbose_name='Nombre del asesor'),
        ),
        migrations.AlterField(
            model_name='cursos',
            name='correo_asesor',
            field=models.EmailField(max_length=254, verbose_name='Correo del asesor'),
        ),
        migrations.AlterField(
            model_name='cursos',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación'),
        ),
        migrations.AlterField(
            model_name='cursos',
            name='descripcion',
            field=models.TextField(verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='cursos',
            name='descuento',
            field=models.BooleanField(verbose_name='Contiene Descuento?'),
        ),
        migrations.AlterField(
            model_name='cursos',
            name='duracion_horas',
            field=models.IntegerField(verbose_name='Duración en Horas'),
        ),
        migrations.AlterField(
            model_name='cursos',
            name='nombre',
            field=models.CharField(max_length=30, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='cursos',
            name='porcentaje_descuento',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4, verbose_name='Descuento Con decimales'),
        ),
        migrations.AlterField(
            model_name='cursos',
            name='precio',
            field=models.IntegerField(verbose_name='Costo'),
        ),
        migrations.AlterField(
            model_name='cursos',
            name='updated',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Actualización'),
        ),
    ]
