# Generated by Django 3.2.4 on 2021-07-06 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0004_auto_20210706_1006'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComentarioContacto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Clave')),
                ('usuario', models.TextField(verbose_name='Usuario')),
                ('apellidos', models.TextField(verbose_name='Usuario')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Registrado')),
                ('estudiante', models.BooleanField(verbose_name='Es Estudiante?')),
                ('correo', models.EmailField(max_length=254, verbose_name='Correo Electronico')),
                ('telefono', models.CharField(max_length=10, verbose_name='Telefono')),
                ('mensaje', models.TextField(verbose_name='Comentario')),
                ('calificacion', models.IntegerField(verbose_name='Calificacion para el sistio Web')),
                ('cursodeinteres', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cursos.cursos', verbose_name='Curso')),
            ],
            options={
                'verbose_name': 'Comentario Contacto',
                'verbose_name_plural': 'Comentarios Contactos',
                'ordering': ['-created'],
            },
        ),
    ]
