# Generated by Django 3.2.4 on 2021-07-06 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0007_auto_20210706_1331'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='opiniones',
            options={'ordering': ['-created'], 'verbose_name': 'Opinion', 'verbose_name_plural': 'Opiniones'},
        ),
    ]
