# Generated by Django 3.2.4 on 2021-07-06 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0008_alter_opiniones_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='opiniones',
        ),
    ]
