# Generated by Django 3.2.4 on 2021-07-06 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0009_delete_opiniones'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ComentarioContacto',
            new_name='Solicita_informacion',
        ),
    ]
