# Generated by Django 3.2.4 on 2021-07-06 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0010_rename_comentariocontacto_solicita_informacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComentarioContacto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Clave')),
                ('usuario', models.TextField(verbose_name='Usuario')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Registrado')),
                ('mensaje', models.TextField(verbose_name='Comentario')),
            ],
            options={
                'verbose_name': 'Comentario Contacto',
                'verbose_name_plural': 'Comentarios Contactos',
                'ordering': ['-created'],
            },
        ),
        migrations.AlterModelOptions(
            name='solicita_informacion',
            options={'ordering': ['-created'], 'verbose_name': 'Solicitud de Informacion', 'verbose_name_plural': 'Solicitudes de Informacion'},
        ),
    ]
