# Generated by Django 3.2.4 on 2021-07-06 21:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0011_auto_20210706_1424'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicita_informacion',
            name='updated',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Actualizadoo'),
            preserve_default=False,
        ),
    ]
