# Generated by Django 3.2.4 on 2021-07-06 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0012_solicita_informacion_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentariocontacto',
            name='apellido',
            field=models.TextField(default=1, verbose_name='Apellido'),
            preserve_default=False,
        ),
    ]
