# Generated by Django 3.2.4 on 2021-07-06 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0014_auto_20210706_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentariocontacto',
            name='imagen',
            field=models.ImageField(null=True, upload_to='fotos', verbose_name='Fotografia'),
        ),
        migrations.AlterField(
            model_name='comentariocontacto',
            name='mensaje',
            field=models.TextField(verbose_name='Comentario'),
        ),
        migrations.AlterField(
            model_name='solicita_informacion',
            name='calificacion',
            field=models.IntegerField(default=0, verbose_name='Calificacion para el sistio Web'),
        ),
    ]
