# Generated by Django 3.2.4 on 2021-07-06 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0015_auto_20210706_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentariocontacto',
            name='imagen',
            field=models.ImageField(null=True, upload_to='fotos_opiniones', verbose_name='Fotografia'),
        ),
    ]
