# Generated by Django 3.2.4 on 2021-07-27 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0016_alter_comentariocontacto_imagen'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cursos',
            options={'ordering': ['-created'], 'verbose_name': 'Cursos', 'verbose_name_plural': 'Cursos'},
        ),
    ]
